-- Seeds the current live site content (courses, dates, FAQ, testimonials, gallery,
-- regulations, der-Weg steps, site settings), generated from src/content/*.ts so
-- the public site is unaffected on cutover to Postgres. Edit via the admin CMS from here on.

-- Auto-generated from src/content/*.ts — seeds the live site's current content.

INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('fahrstunden-auto', 'Fahrstunden Auto', 'Sicher und entspannt zum Autofahren', 'steering-wheel', 'auto', 'auto', 88, 'pro Lektion', 'ab CHF 88 im 10er-Abo', 'Individuelle Fahrstunden in sicheren, komfortablen Autos – auf Wunsch auf Italienisch, Spanisch, Französisch oder Englisch.', '["Moderne, sichere Fahrschulautos","Unterricht in D, IT, FR, ES, EN","Flexible Terminplanung","Vorbereitung auf die praktische Prüfung"]'::jsonb, '["Deutsch","Italienisch","Spanisch","Französisch","Englisch"]'::jsonb, NULL, 'Fahrstunde buchen', '[{"heading":"So läuft deine Fahrstunde ab","body":["Wir holen dich dort ab, wo du stehst – ob erste Fahrstunde überhaupt oder Feinschliff kurz vor der Prüfung. Jede Lektion ist auf dein Tempo und deine Lernziele zugeschnitten.","Unsere Fahrzeuge sind sicher, komfortabel und alltagstauglich – so lernst du in Bedingungen, die du nach der Prüfung auch wirklich antriffst."]},{"heading":"Preise","body":["CHF 95.– pro Lektion (Barzahlung), CHF 90.– im 5er-Abo, CHF 88.– im 10er-Abo.","Einmalige Versicherungspauschale von CHF 100.– bei der ersten Fahrstunde."]},{"heading":"Mehrsprachiger Unterricht","body":["Fährst du dich in deiner Muttersprache sicherer? Kein Problem – wir unterrichten auf Deutsch, Italienisch, Spanisch, Französisch und Englisch."]}]'::jsonb, 0, true);
INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('fahrstunden-motorrad', 'Fahrstunden Motorrad', 'Individuelle Töff-Fahrstunden', 'bike', 'motorrad', 'motorrad', 95, 'pro Lektion', NULL, 'Praxislektionen auf dem Motorrad für alle Kategorien (A1, A beschränkt, A) – individuell begleitet, sicher aufgebaut.', '["Für A1, A (beschränkt) und A","Aufbau von Fahrzeugbeherrschung Schritt für Schritt","Kombinierbar mit dem Motorradgrundkurs","Vorbereitung auf die praktische Prüfung"]'::jsonb, 'null'::jsonb, NULL, 'Fahrstunde buchen', '[{"heading":"Vom ersten Anfahren bis zur Prüfungsroute","body":["Egal ob du gerade erst deinen Lernfahrausweis für die Kategorie A1 gemacht hast oder auf die unbeschränkte Kategorie A hinarbeitest – wir bauen deine Fahrstunden systematisch auf: Fahrzeugbeherrschung, Verkehrssituationen, Prüfungsroute."]},{"heading":"Kombination mit dem Grundkurs","body":["Die praktische Grundausbildung (Motorradgrundkurs) ist obligatorisch und Voraussetzung für die Prüfungsanmeldung. Individuelle Fahrstunden ergänzen den Grundkurs ideal und geben dir zusätzliche Sicherheit im Verkehr."]}]'::jsonb, 0, true);
INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('motorradgrundkurs', 'Motorradgrundkurs', 'Die obligatorische praktische Grundausbildung', 'bike', 'motorrad', 'motorrad', NULL, 'auf Anfrage', NULL, '12 Stunden praktische Grundausbildung – Pflicht für alle Motorrad-Kategorien (A1, A beschränkt, A) vor der praktischen Prüfung.', '["Obligatorisch für A1, A beschränkt und A","Fahrzeugbeherrschung & Gefahrenbremsung","Kleine Gruppen, viel Übungszeit","Kursbestätigung für die Prüfungsanmeldung"]'::jsonb, 'null'::jsonb, '12 Stunden praktische Grundausbildung', 'Kursdatum wählen', '[{"heading":"Was dich erwartet","body":["Die praktische Grundausbildung vermittelt dir die sichere Beherrschung des Motorrads: Balance, Bremstechnik, Ausweichmanöver und Kurvenfahren – in kleinen Gruppen und mit viel individueller Übungszeit auf unserem Verkehrsübungsplatz.","Nach Abschluss erhältst du die Kursbestätigung, die du für die Anmeldung zur praktischen Prüfung benötigst."]},{"heading":"Seit OPERA-3","body":["Seit der Revision OPERA-3 gelten neue Alterslimiten je nach Kategorie (A1 45 km/h ab 15, A1 125cm³ ab 16, A beschränkt 35 kW ab 18, A unbeschränkt ab 20 mit 2 Jahren Vorerfahrung auf einem 35-kW-Motorrad). Wir beraten dich, welche Kategorie und welcher Kurs für dich passt."]}]'::jsonb, 0, true);
INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('vku', 'VKU – Verkehrskunde-Unterricht', 'Der obligatorische Theoriekurs vor den Fahrstunden', 'book-open', 'pflicht', 'vku-btu', 190, 'inkl. Unterlagen', 'ab CHF 190', '4 Doppellektionen, die dich auf sicheres und vorausschauendes Fahren vorbereiten – Pflicht für den Lernfahrausweis Kategorie B.', '["4 Abende, Mo–Do, 19.00–21.00 Uhr","Kleine Klassen, praxisnahe Fallbeispiele","Ab CHF 190 inkl. Kursunterlagen","Regelmässig neue Starttermine"]'::jsonb, 'null'::jsonb, '4 Doppellektionen (Mo–Do, 19.00–21.00 Uhr)', 'VKU-Termin wählen', '[{"heading":"Was ist der VKU?","body":["Der Verkehrskundeunterricht ist in der Schweiz für alle obligatorisch, die den Führerausweis Kategorie B erwerben möchten. In 4 Doppellektionen lernst du vorausschauendes, partnerschaftliches Fahrverhalten – die beste Grundlage für deine Fahrstunden."]},{"heading":"Ablauf & Preis","body":["Der Kurs findet an 4 Abenden statt (Montag bis Donnerstag, jeweils 19.00–21.00 Uhr). Kosten ab CHF 190.– inklusive Kursunterlagen."]}]'::jsonb, 0, true);
INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('btu', 'BTU – Basis-Theorie-Unterricht', 'Fundiertes Theoriewissen für die Prüfung', 'book-open', 'pflicht', 'vku-btu', 200, 'inkl. Unterlagen', NULL, '4 Doppellektionen zu den 6 Theoriethemen – inklusive 8 gratis Übungsstunden Prüfungsfragebogen.', '["4 Doppellektionen zu 6 Theoriethemen","CHF 200 inkl. Kursunterlagen","8 Stunden Prüfungsfragebogen gratis inklusive","Ideale Vorbereitung auf die Theorieprüfung"]'::jsonb, 'null'::jsonb, '4 Doppellektionen', 'BTU-Termin wählen', '[{"heading":"Inhalt","body":["Der Basis-Theorie-Unterricht behandelt die 6 vorgeschriebenen Theoriethemen und bereitet dich gezielt auf die Theorieprüfung vor."]},{"heading":"Inklusive Übungszeit","body":["Im Preis von CHF 200.– (inkl. Unterlagen) sind zusätzlich 8 Stunden gratis Prüfungsfragebogen-Übung (Bögle) enthalten – du übst so lange, bis du dich sicher fühlst."]}]'::jsonb, 0, true);
INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('nothelferkurs', 'Nothelferkurs', 'Pflichtkurs für jedes Führerausweis-Gesuch', 'heart-pulse', 'pflicht', 'nothelfer', NULL, 'siehe Kursdaten', NULL, 'Der erste Schritt auf dem Weg zum Führerausweis: als Wochenendkurs (Fr/Sa) oder als Abendkurs – Ausweis 6 Jahre gültig.', '["Voraussetzung für jedes Führerausweis-Gesuch","Wochenend- oder Abendformat","Ausweis 6 Jahre gültig","Laufend neue Termine"]'::jsonb, 'null'::jsonb, 'Wochenendkurs (Fr–Sa) oder Abendkurs', 'Nothelferkurs buchen', '[{"heading":"Warum zuerst der Nothelferkurs?","body":["Der Nothelferausweis ist Voraussetzung für das Gesuch um einen Lern- oder Führerausweis – deshalb ist er der erste Schritt auf deinem Weg zum Billett."]},{"heading":"Formate","body":["Wähle zwischen dem kompakten Wochenendkurs (Freitag/Samstag) oder Abendlektionen unter der Woche – beide führen zum gleichen, 6 Jahre gültigen Ausweis."]}]'::jsonb, 0, true);
INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('boegle', 'Bögle', 'Gratis Übung für die Theorieprüfung', 'clipboard-check', 'zusatz', 'boegle', 0, 'gratis', 'kostenlos, keine Anmeldung nötig', 'Jeden Montag 19.00–21.00 Uhr übst du bei uns kostenlos den offiziellen Prüfungsfragebogen – in 9 Sprachen verfügbar.', '["Jeden Montag, 19.00–21.00 Uhr (Einlass bis 20.00 Uhr)","Keine Anmeldung nötig, gratis","Prüfung: 50 Fragen, max. 14 Fehler erlaubt","Verfügbar in 9 Sprachen"]'::jsonb, 'null'::jsonb, 'Montags, 19.00–21.00 Uhr', 'Mehr erfahren', '[{"heading":"Was ist Bögle?","body":["„Bögle“ ist unsere kostenlose Übungslektion für die Theorieprüfung. Die echte Prüfung umfasst 50 Fragen mit einer oder mehreren richtigen Antworten – bestanden ist, wer maximal 14 Fehler macht.","Die Theorieprüfung ist in 9 Sprachen verfügbar: Deutsch, Französisch, Italienisch, Englisch, Spanisch, Portugiesisch, Türkisch, Serbokroatisch und Albanisch."]},{"heading":"So funktioniert''s","body":["Komm einfach vorbei – jeden Montag von 19.00 bis 21.00 Uhr (Einlass bis 20.00 Uhr), ohne Anmeldung. Voraussetzung für die Anmeldung zur echten Theorieprüfung ist ein gültiger Nothelferausweis.","Wer vorab testen möchte, ob er bereit ist: Wir bieten zusätzlich einen kostenlosen Mini-Onlinetest mit 20 Beispielfragen an."]}]'::jsonb, 0, true);
INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('lastwagen', 'Lastwagen', 'Fahrausbildung Kategorie C/CE', 'truck', 'zusatz', 'auto', 140, 'pro praktische Lektion', NULL, 'Praktische und theoretische Lektionen für die Lastwagen-Kategorien.', '["CHF 140 pro praktische Lektion","CHF 25 pro theoretische Lektion","Individuelle Terminplanung"]'::jsonb, 'null'::jsonb, NULL, 'Jetzt anfragen', '[{"heading":"Preise","body":["Praktische Lektion: CHF 140.–. Theoretische Lektion: CHF 25.–."]}]'::jsonb, 0, true);
INSERT INTO course (slug, title, tagline, icon, category, audience, price_from, price_unit, price_note, summary, highlights, languages, duration, cta_label, sections, cost_per_session, active) VALUES ('taxi', 'Taxi', 'Ausbildung für den Personentransport', 'car-taxi', 'zusatz', 'auto', 90, 'pro Lektion', NULL, 'Fahrstunden und Vorbereitung für die Taxi-Zulassung.', '["CHF 90 pro Lektion","Individuelle Terminplanung"]'::jsonb, 'null'::jsonb, NULL, 'Jetzt anfragen', '[{"heading":"Preise","body":["CHF 90.– pro Lektion."]}]'::jsonb, 0, true);

INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('a99539e0-b492-47e5-9f58-26b13398e16a', 'vku', 'Mo 20. – Do 23. Juli 2026', '["18.00–20.00 Uhr","20.00–22.00 Uhr"]'::jsonb, '2026-07-20T18:00:00.000Z', 'Verkehrszentrum Baden, Haselstrasse 33', 190, 14);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('81f34604-2961-46d2-853e-e5fe0f5845df', 'vku', 'Mo 3. – Do 6. August 2026', '["18.00–20.00 Uhr","20.00–22.00 Uhr"]'::jsonb, '2026-08-03T18:00:00.000Z', 'Verkehrszentrum Baden, Haselstrasse 33', 190, 14);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('08b6496a-715b-489c-b6df-5af66e7157f1', 'vku', 'Mo 17. – Do 20. August 2026', '["18.00–20.00 Uhr"]'::jsonb, '2026-08-17T18:00:00.000Z', 'Verkehrszentrum Baden, Haselstrasse 33', 190, 3);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('c61558ea-fba5-4c8e-ae83-c126f768007a', 'btu', 'Di 21. – Fr 24. Juli 2026', '["18.00–20.00 Uhr"]'::jsonb, '2026-07-21T18:00:00.000Z', 'Verkehrszentrum Baden, Haselstrasse 33', 200, 14);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('e6a7386a-2147-4a73-a499-4249bf3f89ea', 'btu', 'Di 11. – Fr 14. August 2026', '["18.00–20.00 Uhr"]'::jsonb, '2026-08-11T18:00:00.000Z', 'Verkehrszentrum Baden, Haselstrasse 33', 200, 14);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('73aaddff-9bf1-48c9-a59d-3e5599ceee1f', 'nothelferkurs', 'Fr 25. – Sa 26. Juli 2026', '["Fr 18.00–21.00 Uhr","Sa 08.00–16.00 Uhr"]'::jsonb, '2026-07-25T18:00:00.000Z', 'Verkehrszentrum Baden, Haselstrasse 33', 160, 14);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('b70c20d9-a7cc-4118-976f-b2f42537ac7f', 'nothelferkurs', 'Mo 3. – Do 6. August 2026', '["18.30–21.30 Uhr"]'::jsonb, '2026-08-03T18:00:00.000Z', 'Verkehrszentrum Baden, Haselstrasse 33', 160, 3);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('e9545366-ac78-4088-9f97-84f5ad33f6c5', 'motorradgrundkurs', 'Sa 1. – So 2. August 2026', '["08.00–17.00 Uhr"]'::jsonb, '2026-08-01T18:00:00.000Z', 'Verkehrsübungsplatz Baden', 480, 3);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('172062ad-586a-4f3b-94c2-01e2c30e71f7', 'motorradgrundkurs', 'Sa 22. – So 23. August 2026', '["08.00–17.00 Uhr"]'::jsonb, '2026-08-22T18:00:00.000Z', 'Verkehrsübungsplatz Baden', 480, 14);
INSERT INTO course_date (id, course_slug, date_label, time_slots, starts_at, location, price, capacity) VALUES ('fb35e0a1-f6f4-45e3-9585-8e297c50d053', 'boegle', 'Jeden Montag', '["19.00–21.00 Uhr (Einlass bis 20.00 Uhr)"]'::jsonb, '2026-07-08T06:41:55.892Z', 'Verkehrszentrum Baden, Haselstrasse 33', 0, 14);

INSERT INTO faq_item (question, answer, sort_order) VALUES ('Wie viel kostet der Führerausweis insgesamt?', 'Das hängt von deiner Vorerfahrung und Kategorie ab. Als Richtwert: Nothelferkurs, VKU (ab CHF 190) und rund 10–20 Fahrstunden (ab CHF 88 pro Lektion im Abo) plus die amtlichen Prüfungsgebühren. Wir erstellen dir gerne eine persönliche Kostenschätzung.', 0);
INSERT INTO faq_item (question, answer, sort_order) VALUES ('Wie melde ich mich für einen Kurs an?', 'Wähle unter „Kursdaten & Anmeldung“ dein gewünschtes Datum aus und fülle das Online-Formular aus. Du erhältst danach eine Bestätigung von uns per E-Mail.', 1);
INSERT INTO faq_item (question, answer, sort_order) VALUES ('Was muss ich zur ersten Fahrstunde mitbringen?', 'Deinen Lernfahrausweis, deinen Nothelferausweis sowie bequeme Schuhe. Bei Fragen melde dich einfach vorher bei uns.', 2);
INSERT INTO faq_item (question, answer, sort_order) VALUES ('In welchen Sprachen bietet ihr Unterricht an?', 'Fahrstunden und Theoriekurse bieten wir auf Deutsch, Italienisch, Spanisch, Französisch und Englisch an – sag uns einfach, was für dich am angenehmsten ist.', 3);
INSERT INTO faq_item (question, answer, sort_order) VALUES ('Was ist der Unterschied zwischen VKU und BTU?', 'Der VKU (Verkehrskundeunterricht) ist für alle obligatorisch, die den Führerausweis Kategorie B erwerben. Der BTU (Basis-Theorie-Unterricht) vertieft die 6 Theoriethemen und beinhaltet zusätzlich 8 Stunden gratis Prüfungsfragebogen-Übung.', 4);
INSERT INTO faq_item (question, answer, sort_order) VALUES ('Muss ich mich für „Bögle“ anmelden?', 'Nein – die kostenlose Übungslektion für die Theorieprüfung findet jeden Montag von 19.00 bis 21.00 Uhr (Einlass bis 20.00 Uhr) ohne Anmeldung statt. Einfach vorbeikommen.', 5);
INSERT INTO faq_item (question, answer, sort_order) VALUES ('Wie lange ist der Nothelferausweis gültig?', 'Der Nothelferausweis ist 6 Jahre gültig und Voraussetzung für jedes Führerausweis-Gesuch.', 6);
INSERT INTO faq_item (question, answer, sort_order) VALUES ('Bietet ihr auch Motorrad-Ausbildung an?', 'Ja – von der praktischen Grundausbildung (Motorradgrundkurs) über individuelle Fahrstunden bis zur Vorbereitung auf die praktische Prüfung, für die Kategorien A1, A beschränkt und A.', 7);

INSERT INTO testimonial (name, course, rating, quote, sort_order) VALUES ('Lara M.', 'Fahrstunden Auto', 5, 'Ich war sehr nervös vor meiner ersten Fahrstunde, aber Bruno hat mir die Angst sofort genommen. Erklärt geduldig, bleibt immer ruhig – ich habe die Prüfung im ersten Anlauf bestanden.', 0);
INSERT INTO testimonial (name, course, rating, quote, sort_order) VALUES ('Elira K.', 'VKU & BTU', 5, 'Der Unterricht war super verständlich aufgebaut, auch die Prüfungsfragen im Bögle haben mir enorm geholfen. Danke für die tolle Vorbereitung!', 1);
INSERT INTO testimonial (name, course, rating, quote, sort_order) VALUES ('Marco T.', 'Motorradgrundkurs', 5, 'Kleine Gruppe, viel Übungszeit auf dem Platz und ein Ausbilder, der genau merkt, wo man noch unsicher ist. Kann ich nur empfehlen.', 2);
INSERT INTO testimonial (name, course, rating, quote, sort_order) VALUES ('Sofia R.', 'Fahrstunden Auto (Italienisch)', 5, 'Es war mir wichtig, den Unterricht auf Italienisch zu machen – das hat bei Haudi''s problemlos geklappt und mir viel Sicherheit gegeben.', 3);

INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/a5.jpg', 'Vier Fahrschulautos von Haudi''s Fahrschule aufgereiht vor dem Verkehrszentrum in Baden', 'fahrzeuge', 0);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/a9.jpg', 'VW Golf Cabrio mit Haudi''s Fahrschule Beschriftung', 'fahrzeuge', 1);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/a3.jpg', 'Audi Fahrschulauto von Haudi''s Fahrschule, Frontansicht', 'fahrzeuge', 2);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/a1.gif', 'Reihe von Fahrschulautos mit Haudi''s Schriftzug', 'fahrzeuge', 3);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/a2.gif', 'Fahrschulautos von Haudi''s Fahrschule', 'fahrzeuge', 4);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/a6.jpg', 'Fahrschulauto von Haudi''s Fahrschule', 'fahrzeuge', 5);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/a7.jpg', 'Fahrschulauto von Haudi''s Fahrschule', 'fahrzeuge', 6);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/a8.jpg', 'Fahrschulauto von Haudi''s Fahrschule', 'fahrzeuge', 7);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/t6.jpg', 'Fahrlehrer erklärt eine Verkehrssituation anhand einer Videoprojektion im Schulungsraum', 'verkehrszentrum', 8);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/t3.jpg', 'Heller Schulungsraum im Verkehrszentrum mit Tischreihen für den Theorieunterricht', 'verkehrszentrum', 9);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/t9.jpg', 'Lernende üben gemeinsam Theoriefragen im Verkehrszentrum', 'verkehrszentrum', 10);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/t1.jpg', 'Aufenthaltsbereich im Verkehrszentrum mit Sitzgelegenheiten', 'verkehrszentrum', 11);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/t2.jpg', 'Bereich im Verkehrszentrum Baden', 'verkehrszentrum', 12);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/t4.jpg', 'Schulungsraum im Verkehrszentrum Baden', 'verkehrszentrum', 13);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/t7.jpg', 'Schulungsraum im Verkehrszentrum Baden', 'verkehrszentrum', 14);
INSERT INTO gallery_image (src, alt, category, sort_order) VALUES ('/images/gallery/t8.jpg', 'Schulungsraum im Verkehrszentrum Baden', 'verkehrszentrum', 15);

INSERT INTO regulation_section (vehicle_type, question, answer, sort_order) VALUES ('AUTO', 'Wie läuft der Weg zum Führerausweis Kategorie B seit OPERA-3 ab?', '["Seit der Reform OPERA-3 (in Kraft seit 1. Januar 2021) gilt ein vierstufiges Modell für die Kategorie B (Auto).","1. Theorieprüfung: frühestens ab 17 Jahren möglich, nach Bestehen erhältst du den Lernfahrausweis.","2. Praktische Prüfung: frühestens ab 18 Jahren, Voraussetzung sind 8 Stunden Verkehrskundeunterricht (VKU). Wer den Lernfahrausweis vor dem 20. Altersjahr erwirbt, muss zusätzlich mindestens 1 Jahr Lernphase durchlaufen.","3. Führerausweis auf Probe: gilt 3 Jahre. Innert der ersten 12 Monate ist ein Weiterbildungskurs (WAB, 1 Tag / 7 Stunden) obligatorisch, insgesamt sind 15 Ausbildungsstunden vorgeschrieben.","4. Definitiver Führerausweis: ab 21 Jahren und ohne Widerhandlungen während der Probezeit unbefristet gültig."]'::jsonb, 0);
INSERT INTO regulation_section (vehicle_type, question, answer, sort_order) VALUES ('AUTO', 'Was ändert sich bei Automatik- und Handschaltung?', '["Wer die praktische Prüfung in einem Fahrzeug mit Automatikgetriebe ablegt, darf danach auch manuell geschaltete Fahrzeuge führen – die frühere Einschränkung auf Automatikfahrzeuge wurde per OPERA-3 aufgehoben."]'::jsonb, 1);
INSERT INTO regulation_section (vehicle_type, question, answer, sort_order) VALUES ('AUTO', 'Was passiert, wenn ich den Lernfahrausweis vor dem 20. Altersjahr erwerbe?', '["In diesem Fall ist eine mindestens einjährige Lernphase mit dem Lernfahrausweis vorgeschrieben, bevor du zur praktischen Prüfung antreten kannst."]'::jsonb, 2);
INSERT INTO regulation_section (vehicle_type, question, answer, sort_order) VALUES ('AUTO', 'Was beinhaltet der Weiterbildungskurs (WAB) auf dem Führerausweis auf Probe?', '["Der obligatorische Weiterbildungskurs dauert einen Tag (7 Stunden) und muss innert der ersten 12 Monate nach Erhalt des Führerausweises auf Probe absolviert werden. Schwerpunkte sind unter anderem Gefahrenbremsung und energieeffizientes Fahren."]'::jsonb, 3);
INSERT INTO regulation_section (vehicle_type, question, answer, sort_order) VALUES ('MOTORRAD', 'Was hat sich für Motorradfahrer:innen mit OPERA-3 geändert?', '["OPERA-3 harmonisiert die Schweizer Motorrad-Kategorien mit den EU-Vorgaben und passt die Alterslimiten an. Wer die leistungsstärksten Motorräder (Kategorie A unbeschränkt) fahren will, muss künftig zuerst mindestens 2 Jahre ein auf 35 kW beschränktes Motorrad der Kategorie A gefahren haben."]'::jsonb, 0);
INSERT INTO regulation_section (vehicle_type, question, answer, sort_order) VALUES ('MOTORRAD', 'Welche Kategorien und Alterslimiten gelten?', '["A1 beschränkt (45 km/h): ab 15 Jahren, Theorie- und praktische Prüfung sowie Nothelferausweis nötig, 12 Stunden praktische Grundausbildung.","A1 (125cm³): ab 16 Jahren, 12 Stunden praktische Grundausbildung, Kursbestätigung erforderlich.","A beschränkt (35 kW): ab 18 Jahren, Theorieprüfung (entfällt bei vorhandenem Ausweis Kategorie B), 12 Stunden praktische Grundausbildung, praktische Prüfung.","A unbeschränkt: ab 20 Jahren, sofern mindestens 2 Jahre Fahrpraxis mit einem 35-kW-Motorrad (Kategorie A beschränkt) vorliegen; Einzelfahrstunden und praktische Prüfung."]'::jsonb, 1);
INSERT INTO regulation_section (vehicle_type, question, answer, sort_order) VALUES ('MOTORRAD', 'Ist die praktische Grundausbildung obligatorisch?', '["Ja – die 12-stündige praktische Grundausbildung (unser Motorradgrundkurs) ist für alle Kategorien A1/A Pflicht und Voraussetzung für die Anmeldung zur praktischen Prüfung."]'::jsonb, 2);

INSERT INTO process_step (step, title, description, sort_order) VALUES (1, 'Nothelferkurs absolvieren', 'Bevor du dich für den Lernfahrausweis anmelden kannst, brauchst du einen gültigen Nothelferkurs-Ausweis. Wir bieten den Kurs laufend als Wochenend- oder Abendkurs an – die Bescheinigung ist 6 Jahre gültig.', 0);
INSERT INTO process_step (step, title, description, sort_order) VALUES (2, 'Gesuch einreichen', 'Das Gesuch um einen Lern- oder Fahrausweis lädst du von der Website deines Kantons herunter und reichst es mit Passfoto, Nothelferausweis und einem Sehtest von einem anerkannten Augenarzt oder Optiker ein.', 1);
INSERT INTO process_step (step, title, description, sort_order) VALUES (3, 'Identität bestätigen', 'Mit dem ausgefüllten Gesuch und einem gültigen Ausweisdokument (ID oder Pass) meldest du dich persönlich bei der Einwohnerkontrolle deiner Wohngemeinde.', 2);
INSERT INTO process_step (step, title, description, sort_order) VALUES (4, 'Theorieprüfung bestehen', 'Das Strassenverkehrsamt schickt dir das Aufgebot zur Theorieprüfung zu. Wir helfen dir bei der Vorbereitung – zum Beispiel mit unseren kostenlosen Bögle-Übungslektionen. Nach bestandener Prüfung erhältst du deinen Lernfahrausweis.', 3);
INSERT INTO process_step (step, title, description, sort_order) VALUES (5, 'VKU & Fahrstunden', 'Melde dich bei uns für den Verkehrskundeunterricht (VKU) und deine Fahrstunden an. Wir bilden dich individuell, geduldig und wenn gewünscht in deiner Muttersprache aus.', 4);
INSERT INTO process_step (step, title, description, sort_order) VALUES (6, 'Praktische Prüfung', 'Sobald du und dein/e Fahrlehrer/in bereit seid, meldest du dich zur praktischen Prüfung an. Wir bereiten dich gezielt auf die Prüfungsroute und die häufigsten Situationen vor – und feiern mit dir, wenn du bestanden hast.', 5);

INSERT INTO site_settings (id, name, legal_name, short_name, url, description, phone, phone_display, email, address_street, address_postal_code, address_city, address_region, address_country, geo_latitude, geo_longitude, founders, opening_hours, socials) VALUES (1, 'Haudis Verkehrsschule', 'Haudi''s Fahrschule, Bruno & Ausilia Haudenschild', 'Haudi''s Fahrschule', 'https://www.haudis-verkehrsschule.ch', 'Haudis Verkehrsschule in Baden bildet dich zum Auto- und Motorradfahren aus – mit eigenem, modernem Verkehrszentrum, individueller Betreuung und Unterricht in mehreren Sprachen.', '+41 79 604 44 44', '079 604 44 44', 'info@haudi.ch', 'Haselstrasse 33', '5400', 'Baden', 'AG', 'CH', 47.4788, 8.3104, '["Bruno Haudenschild","Ausilia Haudenschild"]'::jsonb, '[{"days":"Mo–Fr","hours":"08:00–12:00, 13:30–18:30"},{"days":"Sa","hours":"nach Vereinbarung"}]'::jsonb, '[]'::jsonb);
